//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hidistro.UI.Web.KuKaiServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.pub.streetorder.so.bs.nc/ICatchStreetOrderWebInfo", ConfigurationName="KuKaiServiceReference.ICatchStreetOrderWebInfo")]
    public interface ICatchStreetOrderWebInfo {
        
        // CODEGEN: 操作 sendStreetOrderToNC 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://service.pub.streetorder.so.bs.nc/ICatchStreetOrderWebInfo/sendStreetOrderT" +
            "oNC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Hidistro.UI.Web.KuKaiServiceReference.sendStreetOrderToNCResponse1 sendStreetOrderToNC(Hidistro.UI.Web.KuKaiServiceReference.sendStreetOrderToNCRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.pub.streetorder.so.bs.nc/ICatchStreetOrderWebInfo")]
    public partial class sendStreetOrderToNC : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string voField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string vo {
            get {
                return this.voField;
            }
            set {
                this.voField = value;
                this.RaisePropertyChanged("vo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.pub.streetorder.so.bs.nc/ICatchStreetOrderWebInfo")]
    public partial class sendStreetOrderToNCResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnArgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string returnArg {
            get {
                return this.returnArgField;
            }
            set {
                this.returnArgField = value;
                this.RaisePropertyChanged("returnArg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendStreetOrderToNCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.pub.streetorder.so.bs.nc/ICatchStreetOrderWebInfo", Order=0)]
        public Hidistro.UI.Web.KuKaiServiceReference.sendStreetOrderToNC sendStreetOrderToNC;
        
        public sendStreetOrderToNCRequest() {
        }
        
        public sendStreetOrderToNCRequest(Hidistro.UI.Web.KuKaiServiceReference.sendStreetOrderToNC sendStreetOrderToNC) {
            this.sendStreetOrderToNC = sendStreetOrderToNC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendStreetOrderToNCResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.pub.streetorder.so.bs.nc/ICatchStreetOrderWebInfo", Order=0)]
        public Hidistro.UI.Web.KuKaiServiceReference.sendStreetOrderToNCResponse sendStreetOrderToNCResponse;
        
        public sendStreetOrderToNCResponse1() {
        }
        
        public sendStreetOrderToNCResponse1(Hidistro.UI.Web.KuKaiServiceReference.sendStreetOrderToNCResponse sendStreetOrderToNCResponse) {
            this.sendStreetOrderToNCResponse = sendStreetOrderToNCResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatchStreetOrderWebInfoChannel : Hidistro.UI.Web.KuKaiServiceReference.ICatchStreetOrderWebInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatchStreetOrderWebInfoClient : System.ServiceModel.ClientBase<Hidistro.UI.Web.KuKaiServiceReference.ICatchStreetOrderWebInfo>, Hidistro.UI.Web.KuKaiServiceReference.ICatchStreetOrderWebInfo {
        
        public CatchStreetOrderWebInfoClient() {
        }
        
        public CatchStreetOrderWebInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatchStreetOrderWebInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatchStreetOrderWebInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatchStreetOrderWebInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hidistro.UI.Web.KuKaiServiceReference.sendStreetOrderToNCResponse1 Hidistro.UI.Web.KuKaiServiceReference.ICatchStreetOrderWebInfo.sendStreetOrderToNC(Hidistro.UI.Web.KuKaiServiceReference.sendStreetOrderToNCRequest request) {
            return base.Channel.sendStreetOrderToNC(request);
        }
        
        public Hidistro.UI.Web.KuKaiServiceReference.sendStreetOrderToNCResponse sendStreetOrderToNC(Hidistro.UI.Web.KuKaiServiceReference.sendStreetOrderToNC sendStreetOrderToNC1) {
            Hidistro.UI.Web.KuKaiServiceReference.sendStreetOrderToNCRequest inValue = new Hidistro.UI.Web.KuKaiServiceReference.sendStreetOrderToNCRequest();
            inValue.sendStreetOrderToNC = sendStreetOrderToNC1;
            Hidistro.UI.Web.KuKaiServiceReference.sendStreetOrderToNCResponse1 retVal = ((Hidistro.UI.Web.KuKaiServiceReference.ICatchStreetOrderWebInfo)(this)).sendStreetOrderToNC(inValue);
            return retVal.sendStreetOrderToNCResponse;
        }
    }
}
